### ISSUE TITLE
Tarefa 3.2: Adicionar endpoints para busca e filtragem de produtos com base no nome do produto, descrição curta, descrição completa, marca e categoria.

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#24]

**Comment by LucasWithBoots** [comment]
Recurso já foi implementado na branch. Não irei dar merge ainda porque gostaria de implementar pelo menos um teste unitário.

Se já quiser ir implementado a lógica no front, pode usar o branch.
