### ISSUE TITLE
Tarefa 4.2: Configurar a ordenação padrão para nome em ordem ascendente.

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#35]

**Comment by LucasWithBoots** [comment]
`GET /produtos` agora possui dois parâmetros opcionais: `asc` e `page`.

`asc`, se definido para `true`, define a ordem ascendente de acordo com o nome do produto. Por padrão é definido como `true`.
`page`, se não for informado, mostra apenas os primeiros 10 produtos

Em uma implementação futura será relevante mostrar quantas páginas existem no banco dentro da resposta da requisição, mas enquanto isso não acontece, vou marcar como concluído.

![image](https://github.com/user-attachments/assets/8067e333-f6bc-4d98-9a85-949cae7acc60)
![image](https://github.com/user-attachments/assets/9dc90c1d-4686-4631-a920-178a4cc57145)
