### ISSUE TITLE
Criação de usuários - BackEnd

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#43]
**Como administrador do aplicativo BlueVelvet Admin Quero criar um novo usuário com sua respectiva função e status Para ter uma visão centralizada de todos os usuários administradores que têm acesso ao aplicativo Blue Velvet Admin**

- **Requisitos:**

Um formulário deve ser apresentado para coletar dados do usuário. Após enviar o formulário, a lista de usuários deve ser exibida com o novo usuário listado (Veja US-1913 nesta Sprint).

Uma mensagem de sucesso deve ser exibida após o envio do formulário com os dados do usuário (ex.: "Os dados do usuário foram salvos com sucesso").

Em caso de erros, uma mensagem de falha deve ser exibida indicando os problemas encontrados.
O formulário deve conter um botão para cancelar o preenchimento. Quando clicado, o controle deve retornar à visualização de usuários (US-1913 - Listar todos os usuários).

- **Dados do Usuário:**

Um usuário tem os seguintes atributos:

E-mail: Obrigatório, no máximo 128 caracteres.
Primeiro nome: Obrigatório, no máximo 60 caracteres e no mínimo 2 caracteres.
Último nome: Obrigatório, no máximo 60 caracteres e no mínimo 2 caracteres.
Senha: Obrigatório, no máximo 64 caracteres e deve ser codificada antes de ser armazenada no banco de dados (dica: use BCryptPasswordEncoder do Spring Security).
Fotos: Opcional neste Sprint, no máximo 80 caracteres (nome do arquivo no sistema de arquivos).
Habilitado (enabled): Valor booleano (verdadeiro ou falso).
Papéis (roles): Um ou mais papéis (consulte os detalhes em US-2004 nesta Sprint).

**Backend:**

- [x] Criar as tabelas users e users_roles no banco de dados (podem estar vazias inicialmente).

- [x] Implementar a persistência de um usuário no banco de dados com os seguintes cenários de teste: 

- Um usuário associado a um único papel
- Um usuário associado a dois papéis.

- [x] Garantir que o atributo e-mail seja único, com validação para evitar duplicação. Em caso de duplicação, retornar a mensagem: "Há outro usuário com o e-mail fornecido".

- [x] Implementar a codificação da senha antes de salvá-la no banco de dados, utilizando BCryptPasswordEncoder do Spring Security.

- [x] Criar validações para os seguintes requisitos:
- E-mail: Não nulo, máximo de 128 caracteres.
- Senha: Não nula, máximo de 64 caracteres.
- Primeiro nome: Não nulo, entre 2 e 60 caracteres.
- Último nome: Não nulo, entre 2 e 60 caracteres.
- Fotos: Opcional, máximo de 80 caracteres (campo reservado para uso em futuros sprints).

- [x] Implementar API para:
- Listar usuários.
- Adicionar novo usuário.
- Validar dados de entrada e retornar mensagens apropriadas em caso de erro.

**Comment by LucasWithBoots** [comment]
- [ ]  Método deve aceitar arquivos de mídia
- [ ] Mídia deve ser salva em uma pasta específica
