### ISSUE TITLE
Listar Usuários - Backend

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#48]
Como administrador do aplicativo BlueVelvet Admin
Desejo listar todos os usuários com suas respectivas funções e status
Para ter uma visão centralizada de todos os usuários administradores que têm acesso ao aplicativo Blue Velvet Admin.

1. Criação do Endpoint REST

- [x] Criar um endpoint que forneça a lista de usuários administradores com as respectivas funções e status:
   - Método HTTP: GET
   - URL: /api/admin/users
   - Parâmetros: incluir paginação com page e size.
   - Exemplo: /api/admin/users?page=1&size=5.

2. Consulta ao Banco de Dados

- [x] Utilizar o script SQL mencionado no TUS-2141 para popular a tabela de usuários.
- Criar uma consulta SQL que:
   - Filtre apenas usuários com permissões de administrador.
   - Retorne os campos: nome, função e status.
   - Implemente a paginação com LIMIT e OFFSET.

**Comment by LucasWithBoots** [comment]
resolvido no commit 31797aa9f0cf00eb8848f3377048a8567dd21c83
