### ISSUE TITLE
Remover Usuário - Backend

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#51]
Como administrador do aplicativo BlueVelvet Admin
Desejo remover um usuário
Para negar seu acesso futuro ao aplicativo Blue Velvet Admin

1. Criação do Endpoint REST

- Criar um endpoint para remover um usuário:
- Método HTTP: DELETE
- URL: /api/admin/users/{id}
- Parâmetro: {id} (ID do usuário a ser removido).
- 

2. Lógica de Negócio no Serviço

Criar um método no serviço para excluir o usuário:

- Verificar se o usuário com o ID fornecido existe no banco de dados.
- Caso o usuário não exista, lançar uma exceção personalizada (UserNotFoundException).
- Remover o registro do banco de dados.
- Garantir que a operação seja segura e que apenas usuários com permissões adequadas possam executar essa ação.
- 

3. Manipulação de Exceções

- Configurar um ExceptionHandler para lidar com o caso de tentativa de exclusão de um usuário inexistente.
- Retornar uma resposta HTTP 404 com a mensagem "User not found".

**Comment by LucasWithBoots** [comment]
resolvido com o commit d556f5fb0a2b9ac9ba57328fc0900063c650bcf0

não adicionei autenticação com jwt ainda
