### ISSUE TITLE
Login - Frontend

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#58]
Como um usuário que desempenha as funções de administrador, gerente de vendas, editor, gerente de envio e assistente,
Eu quero acessar o Painel de Controle Administrativo do aplicativo BlueVelvet Admin,
Para que eu possa cumprir com minhas responsabilidades administrativas.

- **Interface de Login**  
  - Criar formulário de autenticação com os seguintes campos:  
    - **Email**: Campo de texto para email.  
    - **Senha**: Campo de texto para senha com máscara.  
    - Botão para envio (ex.: "Entrar").  

- **Mensagens de Feedback**  
  - Exibir mensagem de erro visível ao usuário:  
    - **"Email ou senha incorretos. Por favor, tente novamente."**

- **Interação com Backend**  
  - Configurar requisições para os endpoints de login/logout.  
  - Exibir carregamento enquanto a autenticação está sendo processada.  
  - Redirecionar o usuário para o Painel Administrativo após autenticação bem-sucedida.  

- **Sessões**  
  - Implementar lógica de controle para verificar se o usuário está autenticado (ex.: armazenamento local/session storage ou cookies).  
  - Redirecionar para a página de login caso a sessão expire ou o usuário faça logout.

**Comment by LucasWithBoots** [comment]
Implementado no commit 5abedcf24c92a4248e6c9658cb4cca29c2d2dcca
