### ISSUE TITLE
Login - Backend

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#59]
Como um usuário que desempenha as funções de administrador, gerente de vendas, editor, gerente de envio e assistente,
Eu quero acessar o Painel de Controle Administrativo do aplicativo BlueVelvet Admin,
Para que eu possa cumprir com minhas responsabilidades administrativas.

#### **Backend**
- **Configuração da Autenticação**  
  - Implementar validação de autenticação baseada em formulário.  
  - Configurar rotas protegidas para o acesso ao Painel Administrativo.  
  - Implementar armazenamento seguro das credenciais (ex.: hashing de senhas com bcrypt).  
  - Criar endpoints para login e logout.  
  - Gerenciar sessões ou tokens para autenticação (cookies ou JWT).  
  - Implementar verificação de sessão/token para proteger rotas administrativas.  

- **Validação e Feedback**  
  - Desenvolver lógica para verificar email e senha no banco de dados.  
  - Retornar mensagem de erro para credenciais inválidas:  
    - **"Email ou senha incorretos. Por favor, tente novamente."**

- **Gestão de Logout**  
  - Criar endpoint para invalidar sessão/token no logout.  
  - Garantir que o acesso ao Painel Administrativo seja encerrado após logout.

**Comment by LucasWithBoots** [comment]
Já foi implementado
