### ISSUE TITLE
Logout - Backend

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#61]
### **User Story Traduzida**

**Como** um usuário que desempenha as funções de administrador, gerente de vendas, editor, gerente de envio e assistente,  
**Eu quero** sair do Painel de Controle Administrativo do aplicativo BlueVelvet Admin,  
**Para que** uma pessoa não autorizada não utilize minha sessão.

#### **Backend**
- **Gestão de Logout**
  - Criar endpoint para logout que invalida a sessão/token do usuário.  
  - Garantir que o acesso ao Painel Administrativo seja bloqueado após o logout.  
  - Implementar lógica no servidor para impedir o uso de sessões/tokens expirados ou inválidos.

- **Testes**
  - Simular um cenário de logout e tentar acessar o sistema novamente sem autenticação.  
  - Garantir que o sistema retorne erro de autenticação e redirecione para a página de login.

**Comment by LucasWithBoots** [comment]
Implementado
