### ISSUE TITLE
Controle de Acesso por Funções - Backend

### ISSUE THREAD

**Issue by Dogolaa** [Dogolaa/MusicStore#65]
**Como** um usuário que desempenha as funções de administrador, gerente de vendas, editor, gerente de envio e assistente,  
**Eu quero** acessar apenas as funcionalidades do aplicativo para as quais tenho autorização,  
**Para que** eu evite realizar ações que não me são permitidas.

---

#### **Critérios de Aceitação**
- **Testes:**
  - Um **gerente de vendas** **não pode** usar funcionalidades associadas a:  
    - Lista de usuários administradores.  
    - Categorias de produtos.  
    - Marcas.  
    - Artigos.  
    - Menus.  
    - Configurações.  
  - Um **administrador** tem autorização para usar **TODAS** as funcionalidades do aplicativo administrativo.  
  - Um **gerente de envio** pode acessar funcionalidades relacionadas a **pedidos** e **produtos associados**.  

---

#### **Backend**
- **Gestão de Permissões**
  - Definir níveis de permissão com base nos papéis dos usuários:
    - **Administrador**: acesso total.  
    - **Gerente de vendas**: acesso restrito às funcionalidades permitidas.  
    - **Gerente de envio**: acesso às funcionalidades relacionadas a pedidos e produtos associados.  
  - Implementar middleware ou lógica no servidor para verificar permissões antes de permitir o acesso a rotas específicas.  

- **Configuração de Controle de Acesso**
  - Criar estrutura de controle de acesso baseada em funções (Role-Based Access Control - RBAC).  
  - Mapear funcionalidades específicas às permissões de cada papel.  

- **Testes**
  - Garantir que usuários com permissões inadequadas sejam bloqueados ao tentar acessar funcionalidades restritas.  
  - Validar que o acesso autorizado funcione corretamente para cada papel.

**Comment by LucasWithBoots** [comment]
Implementado no commit aadd04b4d35bc5a54bd7b3157368fbe066e5a0e7
